rm ../../export/relation/*.*
#Exportar endereços do texto completo
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"AtoZ: novas praticas em informacao e conhecimento"}' --out ../../export/relation/relation_atoz.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Biblionline"}' --out ../../export/relation/relation_biblionline.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Biblioteca Escolar em Revista"}' --out ../../export/relation/relation_biblioteca_escolar_em_revista.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Bibliotecas Universitarias: Pesquisas, experiencias e perspectivas"}' --out ../../export/relation/relation_bus.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Biblos"}' --out ../../export/relation/relation_biblos.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Brazilian Journal of Information Science"}' --out ../../export/relation/relation_bjis.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Cadernos de Informacao Juridica"}' --out ../../export/relation/relation_cij.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Ciencia da Informacao em Revista"}' --out ../../export/relation/relation_cir.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"EmQuestao"}' --out ../../export/relation/relation_emquestao.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Encontros Bibli"}' --out ../../export/relation/relation_encontros_bibli.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Folha de Rosto"}' --out ../../export/relation/relation_folhaderosto.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"IRIS"}' --out ../../export/relation/relation_iris.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"InCID"}' --out ../../export/relation/relation_incid.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Informacao e Informacao"}' --out ../../export/relation/relation_infoeinfo.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Informacao e Sociedade: Estudos"}' --out ../../export/relation/relation_infoesociedade.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Informacao e Tecnologia - ITEC"}' --out ../../export/relation/relation_itec.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Informacao@Profissoes"}' --out ../../export/relation/relation_info_profissoes.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Liinc em Revista"}' --out ../../export/relation/relation_liinc.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"PBCIB"}' --out ../../export/relation/relation_pbcib.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Perspectivas em Ciencia da Informacao"}' --out ../../export/relation/relation_pci.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Perspectivas em Gestao e Conhecimento"}' --out ../../export/relation/relation_pgc.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"PontodeAcesso"}' --out ../../export/relation/relation_pontodeacesso.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"RECIIS"}' --out ../../export/relation/relation_reciis.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Revista ACB"}' --out ../../export/relation/relation_acb.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Revista Brasileira de Biblioteconomia e Documentacao"}' --out ../../export/relation/relation_rbbd.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Revista Brasileira de Educacao em Ciencia da Informacao"}' --out ../../export/relation/relation_rebecin.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Revista Ciencia da Informacao"}' --out ../../export/relation/relation_ciinf.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Revista Digital de Biblioteconomia e Ciencia da Informacao"}' --out ../../export/relation/relation_rdbci.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Revista Ibero Americana de Ciencia da Informacao"}' --out ../../export/relation/relation_riaci.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Tendencias da Pesquisa Brasileira em Ciencia da Informacao"}' --out ../../export/relation/relation_tendencias.csv
#mongoexport --db journals --collection ci --type=csv --fields _id,relation --query '{"journalci_title":"Transinformacao"}' --out ../../export/relation/relation_transinformacao.csv
